# -*- coding: utf-8 -*-
"""Simple Linear Regression Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lKzQ8-efp4xdhBd6jWcsQWFlFYgi7iZ
"""

!pip install -U scikit-learn==1.9.0

import sklearn
print(sklearn.__version__)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Salary_Data.csv")

df.head()

df.info()

df.isnull().sum()

df.describe()

X = df[['YearsExperience']]
y = df['Salary']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

plt.figure(figsize=(8,5))

plt.scatter(X, y, color="blue", label="Actual Data")

plt.plot(X, model.predict(X), color="red", label="Regression Line")

plt.title("Salary Prediction using Simple Linear Regression")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.legend()

plt.show()

result = pd.DataFrame({
    "Actual Salary": y_test.values,
    "Predicted Salary": y_pred
})

result

experience = pd.DataFrame({'YearsExperience': [5]})

predicted_salary = model.predict(experience)

print("Predicted Salary:", predicted_salary[0])

import joblib

joblib.dump(model, "salary_model.pkl")

print("Model Saved Successfully!")

result.to_csv("Prediction_Results.csv", index=False)

print("Prediction Results Saved Successfully!")